# Generated by Django 4.2.4 on 2023-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='materials/')),
            ],
        ),
    ]
