# Generated by Django 4.2.4 on 2023-08-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.outline'),
        ),
    ]
