# Generated by Django 4.2.4 on 2023-08-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='department',
        ),
        migrations.RemoveField(
            model_name='material',
            name='level',
        ),
    ]
