# Generated by Django 4.2.4 on 2023-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_material_department_remove_material_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
