# Generated by Django 4.2.4 on 2023-08-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_material_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.FileField(default='', upload_to='courses/outlines/'),
            preserve_default=False,
        ),
    ]
