# Generated by Django 4.2.4 on 2023-08-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0009_alter_coursecomment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respond', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='sub_topics',
        ),
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.FileField(null=True, upload_to='courses/outlines/'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='modified',
            field=models.FileField(null=True, upload_to='timetable/mod/'),
        ),
        migrations.DeleteModel(
            name='Outline',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddIndex(
            model_name='flaggedissue',
            index=models.Index(fields=['content_type', 'object_id'], name='app_flagged_content_cbf221_idx'),
        ),
    ]
