# Generated by Django 4.2.4 on 2023-08-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_flaggedissue_remove_topic_sub_topics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggedissue',
            old_name='respond',
            new_name='response',
        ),
    ]
