# Generated by Django 4.2.4 on 2023-08-25 11:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_respond_flaggedissue_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to=app.models.materials_directory_path),
        ),
    ]
