# Generated by Django 4.2.4 on 2023-08-26 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0002_remove_account_plan_plan_user_plantype_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
